version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ssh-tunnel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: logs
      MYSQL_USER: tunnel_user
      MYSQL_PASSWORD: tunnel_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - tunnel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Relay Server
  relay:
    build: .
    container_name: ssh-tunnel-relay
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: tunnel_user
      DB_PASSWORD: tunnel_pass
      DB_NAME: logs
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      USER_USERNAME: user
      USER_PASSWORD: user123
    ports:
      - "8080:8080"
    volumes:
      - relay_logs:/app/logs
    networks:
      - tunnel-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 10s
      retries: 5
      start_period: 30s

  # PostgreSQL Database (for testing)
  postgres:
    image: postgres:15
    container_name: ssh-tunnel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tunnel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      timeout: 20s
      retries: 10

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ssh-tunnel-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - tunnel-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  relay_logs:
    driver: local

networks:
  tunnel-network:
    driver: bridge